/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Dheta Delv-Indra
 */
public class admintambah extends javax.swing.JFrame {

    /**
     * Creates new form AdminUbahObat
     */
    public admintambah() {
        initComponents();
    }
    
    public void setNamaAdmin(String a){
         namaAdmin.setText(a);
    }
    
    
    public void setJumlah(int a){
        stok.setValue(a);
    }
    
    public String getJumlah(){
        return stok.getValue().toString();
    }
    
    public String getNama(){
        return nama.getText();
    }
    
    public void simpanListener(ActionListener a){
        simpandata.addActionListener (a);
    }
    
    public void berandaListener(ActionListener a){
        beranda.addActionListener(a);
    }
    
    public void pasienListener (ActionListener a){
        pasien.addActionListener(a);
    }
    
    public void kembaliListener (ActionListener a){
        back.addActionListener(a);
    }
    
    public JButton obatB(){
        return obat;
    }
    
    public JButton berandaB(){
        return beranda;
    }
    
    public JButton pasienB(){
        return pasien;
    }
    
    public void obatListener (ActionListener a){
        obat.addActionListener(a);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stok = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        simpandata = new javax.swing.JButton();
        namaAdmin = new javax.swing.JLabel();
        pasien = new javax.swing.JButton();
        obat = new javax.swing.JButton();
        beranda = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 80, 30));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel2.setText("Stok               :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 90, 30));

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel3.setText("Nama Obat   :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 90, 30));

        simpandata.setBackground(new java.awt.Color(255, 255, 204));
        simpandata.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        simpandata.setForeground(new java.awt.Color(89, 133, 39));
        simpandata.setText("Simpan data obat");
        getContentPane().add(simpandata, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, 40));

        namaAdmin.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        namaAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(namaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 180, 30));

        pasien.setBackground(new java.awt.Color(89, 133, 39));
        pasien.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        pasien.setForeground(new java.awt.Color(255, 255, 204));
        pasien.setText("Data Pasien");
        getContentPane().add(pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 150, 40));

        obat.setBackground(new java.awt.Color(89, 133, 39));
        obat.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        obat.setForeground(new java.awt.Color(255, 255, 204));
        obat.setText("Data Obat");
        getContentPane().add(obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 140, 40));

        beranda.setBackground(new java.awt.Color(89, 133, 39));
        beranda.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 204));
        beranda.setText("Beranda");
        getContentPane().add(beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 40));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 140, 30));

        back.setBackground(new java.awt.Color(255, 255, 204));
        back.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(89, 133, 39));
        back.setText("Kembali");
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 280, 110, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/admin.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admintambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admintambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admintambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admintambah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admintambah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton beranda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nama;
    private javax.swing.JLabel namaAdmin;
    private javax.swing.JButton obat;
    private javax.swing.JButton pasien;
    private javax.swing.JButton simpandata;
    private javax.swing.JSpinner stok;
    // End of variables declaration//GEN-END:variables
}
