/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dheta
 */
public class AdminDaftarPasien extends javax.swing.JFrame {

    /**
     * Creates new form AdminDaftarPasien
     */
    public AdminDaftarPasien() {
        initComponents();
    }

    public void setNama(String nama) {
        namaAdmin.setText(nama);
    }

    public JButton detail() {
        return detailRMD;
    }

    public JTable getTabel() {
        return listPasien;
    }

    public void setTabelPasien(DefaultTableModel t) {
        listPasien.setModel(t);
    }

    public void tableListener(MouseListener m) {
        listPasien.addMouseListener(m);
    }

    public void cariButtonListener(ActionListener a) {
        cariButon.addActionListener(a);
    }

    public void detailListener(ActionListener b) {
        detailRMD.addActionListener(b);
    }

    public void tambahListener(ActionListener c) {
        tambah.addActionListener(c);
    }
    
    public void berandaListener(ActionListener c) {
        beranda.addActionListener(c);
    }
    
    public void obatListener(ActionListener c) {
        obat.addActionListener(c);
    }
    
    public JButton pasienB(){
        return pasien;
    }

    public String getCariPasien() {
        return cariTeks.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPasien = new javax.swing.JTable();
        cariTeks = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cariButon = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        detailRMD = new javax.swing.JButton();
        beranda = new javax.swing.JButton();
        obat = new javax.swing.JButton();
        pasien = new javax.swing.JButton();
        namaAdmin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(listPasien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 650, 330));

        cariTeks.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(cariTeks, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 240, 30));

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel1.setText("Cari Nama Pasien:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 164, -1, 40));

        cariButon.setBackground(new java.awt.Color(255, 255, 204));
        cariButon.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        cariButon.setForeground(new java.awt.Color(89, 133, 39));
        cariButon.setText("Cari");
        getContentPane().add(cariButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 70, 30));

        tambah.setBackground(new java.awt.Color(255, 255, 204));
        tambah.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        tambah.setForeground(new java.awt.Color(89, 133, 39));
        tambah.setText("Tambah Pasien");
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, 30));

        detailRMD.setBackground(new java.awt.Color(102, 204, 0));
        detailRMD.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        detailRMD.setForeground(new java.awt.Color(255, 255, 153));
        detailRMD.setText("Lihat Rekamedis Pasien");
        detailRMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailRMDActionPerformed(evt);
            }
        });
        getContentPane().add(detailRMD, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 170, 40));

        beranda.setBackground(new java.awt.Color(89, 133, 39));
        beranda.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 204));
        beranda.setText("Beranda");
        getContentPane().add(beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 40));

        obat.setBackground(new java.awt.Color(89, 133, 39));
        obat.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        obat.setForeground(new java.awt.Color(255, 255, 204));
        obat.setText("Data Obat");
        getContentPane().add(obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 140, 40));

        pasien.setBackground(new java.awt.Color(89, 133, 39));
        pasien.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        pasien.setForeground(new java.awt.Color(255, 255, 204));
        pasien.setText("Data Pasien");
        getContentPane().add(pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 150, 40));

        namaAdmin.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        namaAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(namaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 210, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/admin.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detailRMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailRMDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailRMDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDaftarPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDaftarPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDaftarPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDaftarPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDaftarPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beranda;
    private javax.swing.JButton cariButon;
    private javax.swing.JTextField cariTeks;
    private javax.swing.JButton detailRMD;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listPasien;
    private javax.swing.JLabel namaAdmin;
    private javax.swing.JButton obat;
    private javax.swing.JButton pasien;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
