/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Dheta Delv-Indra
 */
public class DokterPeriksa2 extends javax.swing.JFrame {

    /**
     * Creates new form DokterPeriksa
     */
    
   
   // private JScrollPane scrollAnamnesa, scrollDiagnosa, scrollKhusus, scrollTambahan;
    
    public DokterPeriksa2() {
        initComponents();
    }
    
    public void setAnamnesa(String a){
         anamnesa.setText(a);
    }
    
    public void setNama(String aa){
        username.setText(aa);
    }
    
    public void setAlamat(String aa){
        alamat.setText(aa);
    }
    public void setKerja(String aa){
        kerja.setText(aa);
    }
    
    public void setNamaPasien(String a){
        setNamaPasien.setText(a);
    }
    
    public void setUsia(String a){
        setUsia.setText(a);
    }
    
    public void setPekerjaan(String a){
        setPekerjaan.setText(a);
    }
    
    public void setTensi (String a){
        tensi.setText(a);
    }
    
    public void setRR (String a){
        rr.setText(a);
    }
    
    public void setSuhu(String a){
        suhu.setText(a);
    }
    
    public void setNadi(String a){
        nadi.setText(a);
    }
    
    public String getAnamnesa(){
        return anamnesa.getText();
    }
    
    public String getTensi(){
        return tensi.getText();
    }
    
    public String getRR(){
        return rr.getText();
    }
    
    public String getSuhu(){
        return suhu.getText();
    }
    
    public String getNadi(){
        return nadi.getText();
    }
    
    public String getKhusus(){
        return khusus.getText();
    }
    
    public String getTambahan(){
        return tambahan.getText();
    }
    
    public String getDiagnosa(){
        return diagnosa.getText();
    }
    
    public JTextArea anam(){
      return anamnesa;
    }
    
    public JTextArea khusus(){
        return khusus;
    }
    
    public JTextArea tambahan(){
        return tambahan;
    }
    
    public JTextArea diagnosa(){
        return diagnosa;
    }
    
    public JTextField suhu(){
        return suhu;
    }

    public JTextField nadi(){
        return nadi;
    }

    public JTextField rr(){
        return rr;
    }

    public JTextField tensi(){
        return tensi;
    }

    public void simpanData(ActionListener a){
        simpan.addActionListener(a);
    }
    
    public void keluarya(ActionListener a){
        keluar.addActionListener(a);
    }
    
    public void karyawanya(ActionListener a){
        karyawan.addActionListener(a);
    }
    
    public void berandaya(ActionListener a){
        beranda.addActionListener(a);
    }
    
    public void obatya(ActionListener a){
        dataobat.addActionListener(a);
    }
    
    public void pasienya(ActionListener a){
        datapasien.addActionListener(a);
    }
        
    public JButton save(){
        return simpan;
    }

    public JButton karyawanB(){
    	return karyawan;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        setPekerjaan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        scrollAnamnesa = new javax.swing.JScrollPane();
        anamnesa = new javax.swing.JTextArea();
        scrollTambahan = new javax.swing.JScrollPane();
        tambahan = new javax.swing.JTextArea();
        scrollDiagnosa = new javax.swing.JScrollPane();
        diagnosa = new javax.swing.JTextArea();
        scrollKhusus = new javax.swing.JScrollPane();
        khusus = new javax.swing.JTextArea();
        suhu = new javax.swing.JTextField();
        tensi = new javax.swing.JTextField();
        nadi = new javax.swing.JTextField();
        kerja = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        rr = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        setUsia = new javax.swing.JLabel();
        setNamaPasien = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        karyawan = new javax.swing.JButton();
        dataobat = new javax.swing.JButton();
        datapasien = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        beranda = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel1.setText("Periksa Hari Ini:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel2.setText("mmHg");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, 20));

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel3.setText("Usia   :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 30));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel4.setText("Alamat     :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, 30));
        getContentPane().add(setPekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 100, 20));

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel7.setText("Tensi     :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel8.setText("Pemeriksaan Tambahan:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 160, 40));

        jLabel9.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel9.setText("RR         :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel10.setText("Nadi      :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        jLabel11.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel11.setText("Diagnosa:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel12.setText("Pemeriksaan Khusus:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));

        anamnesa.setColumns(20);
        anamnesa.setRows(5);
        scrollAnamnesa.setViewportView(anamnesa);

        getContentPane().add(scrollAnamnesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 230, 60));

        tambahan.setColumns(20);
        tambahan.setRows(5);
        scrollTambahan.setViewportView(tambahan);

        getContentPane().add(scrollTambahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 300, 60));

        diagnosa.setColumns(20);
        diagnosa.setRows(5);
        scrollDiagnosa.setViewportView(diagnosa);

        getContentPane().add(scrollDiagnosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 300, 60));

        khusus.setColumns(20);
        khusus.setRows(5);
        scrollKhusus.setViewportView(khusus);

        getContentPane().add(scrollKhusus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 300, 60));

        suhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suhuActionPerformed(evt);
            }
        });
        getContentPane().add(suhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 70, 30));

        tensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tensiActionPerformed(evt);
            }
        });
        getContentPane().add(tensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 70, 30));
        getContentPane().add(nadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 70, 30));

        kerja.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(kerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 230, 30));

        alamat.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 230, 30));
        getContentPane().add(rr, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 70, 30));

        jLabel13.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel13.setText("Nama :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 30));

        setUsia.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(setUsia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 120, 30));

        setNamaPasien.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(setNamaPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 230, 30));

        simpan.setBackground(new java.awt.Color(255, 255, 204));
        simpan.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        simpan.setForeground(new java.awt.Color(89, 133, 39));
        simpan.setText("Simpan Data Periksa");
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, -1, 40));

        jLabel14.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel14.setText("Anamnesa :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        keluar.setBorder(null);
        keluar.setBorderPainted(false);
        keluar.setContentAreaFilled(false);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 50, 40));

        username.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        username.setText("tes");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 240, 20));

        karyawan.setBackground(new java.awt.Color(89, 133, 39));
        karyawan.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        karyawan.setForeground(new java.awt.Color(255, 255, 204));
        karyawan.setText("Data Karyawan");
        getContentPane().add(karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, 40));

        dataobat.setBackground(new java.awt.Color(89, 133, 39));
        dataobat.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        dataobat.setForeground(new java.awt.Color(255, 255, 204));
        dataobat.setText("Data Obat");
        dataobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataobatActionPerformed(evt);
            }
        });
        getContentPane().add(dataobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 140, 40));

        datapasien.setBackground(new java.awt.Color(89, 133, 39));
        datapasien.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        datapasien.setForeground(new java.awt.Color(255, 255, 204));
        datapasien.setText("Data Pasien");
        getContentPane().add(datapasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 40));

        jLabel16.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel16.setText("C");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, 20));

        jLabel15.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel15.setText("Suhu     :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        beranda.setBackground(new java.awt.Color(89, 133, 39));
        beranda.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 204));
        beranda.setText("Beranda");
        getContentPane().add(beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 40));

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel6.setText("Pekerjaan :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/admin.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void dataobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataobatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataobatActionPerformed

    private void suhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suhuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suhuActionPerformed

    private void tensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tensiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tensiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DokterPeriksa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DokterPeriksa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DokterPeriksa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DokterPeriksa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DokterPeriksa2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JTextArea anamnesa;
    private javax.swing.JButton beranda;
    private javax.swing.JButton dataobat;
    private javax.swing.JButton datapasien;
    private javax.swing.JTextArea diagnosa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton karyawan;
    private javax.swing.JButton keluar;
    private javax.swing.JLabel kerja;
    private javax.swing.JTextArea khusus;
    private javax.swing.JTextField nadi;
    private javax.swing.JTextField rr;
    private javax.swing.JScrollPane scrollAnamnesa;
    private javax.swing.JScrollPane scrollDiagnosa;
    private javax.swing.JScrollPane scrollKhusus;
    private javax.swing.JScrollPane scrollTambahan;
    private javax.swing.JLabel setNamaPasien;
    private javax.swing.JLabel setPekerjaan;
    private javax.swing.JLabel setUsia;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField suhu;
    private javax.swing.JTextArea tambahan;
    private javax.swing.JTextField tensi;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
