/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.obat;
import model.pasien;
import model.user;

/**
 *
 * @author Dheta Delv-Indra
 */
public class DokterIsiResep extends javax.swing.JFrame {

    /**
     * Creates new form DokterIsiResep
     */
    Connection konek;
    obat modelObat;
    pasien modelPasien;
    String obatCombo[][];

    public DokterIsiResep() {
        obat = new JComboBox();
        modelObat = new obat();
        obatCombo = modelObat.getDaftarObat();

        initComponents();
    }

    public void setIDRMD(String idRMD) {
        id.setText(idRMD);
    }

    public void setUser(String a) {
        username.setText(a);
    }

    public void tambahkeresep(ActionListener a) {
        masukkanKeDaftar.addActionListener(a);
    }

    public void selesairesep(ActionListener a) {
        selesai.addActionListener(a);
    }

    public String getObat() {
        int indeks = obat.getSelectedIndex();
        return obatCombo[0][indeks];
    }

    public String getKeterangan() {
        return keterangan.getText();
    }

    public String getJumlah() {
        return jumlah.getValue().toString();
    }

    public String getSigna() {
        return signa.getText();
    }

    public void setTabel(DefaultTableModel t) {
        tabelObat.setModel(t);
    }

    public JTable getTabel() {
        return tabelObat;
    }

    public void setSigna(String a) {
        signa.setText(a);
    }

    public void setKet(String a) {
        keterangan.setText(a);
    }

    public void setJumlah(int a) {
        jumlah.setValue(a);
    }

    public JComboBox komboobat() {
        return obat;
    }

    public JButton karyawanB() {
        return karyawan;
    }

    public void pasienListener(ActionListener a) {
        datapasien.addActionListener(a);
    }

    public void berandaListener(ActionListener a) {
        beranda.addActionListener(a);
    }

    public void obatListener(ActionListener a) {
        dataobat.addActionListener(a);
    }

    public void keluarListener(ActionListener a) {
        keluar.addActionListener(a);
    }
    
    public void karyawanListener(ActionListener a){
        karyawan.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelObat = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        obat = new javax.swing.JComboBox(obatCombo[1]);
        jumlah = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        masukkanKeDaftar = new javax.swing.JButton();
        selesai = new javax.swing.JButton();
        keterangan = new javax.swing.JTextField();
        signa = new javax.swing.JTextField();
        beranda = new javax.swing.JButton();
        datapasien = new javax.swing.JButton();
        dataobat = new javax.swing.JButton();
        karyawan = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Obat", "Jumlah Obat", "Signa", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(tabelObat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 510, 210));

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel1.setText("Jumlah:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel4.setText("Obat:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        obat.setModel(new javax.swing.DefaultComboBoxModel(obatCombo[1]));
        getContentPane().add(obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 200, 30));
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 40, 30));

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel5.setText("Signa:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel7.setText("Keterangan:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        masukkanKeDaftar.setBackground(new java.awt.Color(255, 255, 204));
        masukkanKeDaftar.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        masukkanKeDaftar.setForeground(new java.awt.Color(89, 133, 39));
        masukkanKeDaftar.setText("Tambahkan obat ke resep");
        getContentPane().add(masukkanKeDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, 30));

        selesai.setBackground(new java.awt.Color(204, 255, 204));
        selesai.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        selesai.setForeground(new java.awt.Color(89, 133, 39));
        selesai.setText("Selesai membuat resep");
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });
        getContentPane().add(selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 170, 30));
        getContentPane().add(keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 210, 30));
        getContentPane().add(signa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 210, 30));

        beranda.setBackground(new java.awt.Color(89, 133, 39));
        beranda.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 204));
        beranda.setText("Beranda");
        getContentPane().add(beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 40));

        datapasien.setBackground(new java.awt.Color(89, 133, 39));
        datapasien.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        datapasien.setForeground(new java.awt.Color(255, 255, 204));
        datapasien.setText("Data Pasien");
        getContentPane().add(datapasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 40));

        dataobat.setBackground(new java.awt.Color(89, 133, 39));
        dataobat.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        dataobat.setForeground(new java.awt.Color(255, 255, 204));
        dataobat.setText("Data Obat");
        dataobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataobatActionPerformed(evt);
            }
        });
        getContentPane().add(dataobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 140, 40));

        karyawan.setBackground(new java.awt.Color(89, 133, 39));
        karyawan.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        karyawan.setForeground(new java.awt.Color(255, 255, 204));
        karyawan.setText("Data Karyawan");
        getContentPane().add(karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, 40));

        username.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        username.setText("tes");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 210, 20));

        keluar.setBorder(null);
        keluar.setBorderPainted(false);
        keluar.setContentAreaFilled(false);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 50, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/admin.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 70, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataobatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataobatActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DokterIsiResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DokterIsiResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DokterIsiResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DokterIsiResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DokterIsiResep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beranda;
    private javax.swing.JButton dataobat;
    private javax.swing.JButton datapasien;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jumlah;
    private javax.swing.JButton karyawan;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField keterangan;
    private javax.swing.JButton masukkanKeDaftar;
    private javax.swing.JComboBox obat;
    private javax.swing.JButton selesai;
    private javax.swing.JTextField signa;
    private javax.swing.JTable tabelObat;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
