/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import model.pasien;
import model.user;

/**
 *
 * @author Dheta Delv-Indra
 */
public class DokterTambahKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form AdminUbahObat
     */

    public DokterTambahKaryawan() {
        
    
        initComponents();
    }
    
    

    public void setNamaAdmin(String a) {
        namaAdmin.setText(a);
    }


    public void simpan(ActionListener a) {
        simpandata.addActionListener(a);
    }

    public void berandaListener(ActionListener a) {
        beranda.addActionListener(a);
    }

    public void pasienListener(ActionListener a) {
        pasien.addActionListener(a);
    }

    public JButton obatB() {
        return obat;
    }

    public JButton berandaB() {
        return beranda;
    }

    public JButton pasienB() {
        return pasien;
    }
    
    public JButton karyawanB(){
        return karyawan;
    }

    public void obatListener(ActionListener a) {
        obat.addActionListener(a);
    }

    public void mbalekListener(ActionListener a) {
        back.addActionListener(a);
    }

    public void keluaroi(ActionListener a) {
        keluar.addActionListener(a);
    }
    
    public String getUsername(){
        return uname.getText();
    }
    
    public String getPass(){
        return pass.getText();
    }
    
    public String getNamanya(){
        return nama.getText();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        simpandata = new javax.swing.JButton();
        pasien = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        obat = new javax.swing.JButton();
        beranda = new javax.swing.JButton();
        back = new javax.swing.JButton();
        namaAdmin = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        pass = new javax.swing.JTextField();
        karyawan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel3.setText("Nama          :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 90, 30));

        simpandata.setBackground(new java.awt.Color(255, 255, 204));
        simpandata.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        simpandata.setForeground(new java.awt.Color(89, 133, 39));
        simpandata.setText("Simpan data");
        getContentPane().add(simpandata, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, 40));

        pasien.setBackground(new java.awt.Color(89, 133, 39));
        pasien.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        pasien.setForeground(new java.awt.Color(255, 255, 204));
        pasien.setText("Data Pasien");
        getContentPane().add(pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 40));

        nama.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 270, 30));

        obat.setBackground(new java.awt.Color(89, 133, 39));
        obat.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        obat.setForeground(new java.awt.Color(255, 255, 204));
        obat.setText("Data Obat");
        getContentPane().add(obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 140, 40));

        beranda.setBackground(new java.awt.Color(89, 133, 39));
        beranda.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 204));
        beranda.setText("Beranda");
        getContentPane().add(beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 40));

        back.setBackground(new java.awt.Color(255, 255, 204));
        back.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(89, 133, 39));
        back.setText("Kembali");
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 100, 40));

        namaAdmin.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        namaAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        namaAdmin.setText("tes");
        getContentPane().add(namaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 70, 20));

        uname.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 270, 30));

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel5.setText("Password     :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 90, 30));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel4.setText("Username    :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 90, 30));

        keluar.setBorder(null);
        keluar.setBorderPainted(false);
        keluar.setContentAreaFilled(false);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 50, 40));

        pass.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 270, 30));

        karyawan.setBackground(new java.awt.Color(89, 133, 39));
        karyawan.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        karyawan.setForeground(new java.awt.Color(255, 255, 204));
        karyawan.setText("Data Karyawan");
        getContentPane().add(karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/admin.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DokterTambahKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DokterTambahKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DokterTambahKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DokterTambahKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DokterTambahKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton beranda;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton karyawan;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField nama;
    private javax.swing.JLabel namaAdmin;
    private javax.swing.JButton obat;
    private javax.swing.JButton pasien;
    private javax.swing.JTextField pass;
    private javax.swing.JButton simpandata;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
