/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dheta Delv-Indra
 */
public class DokterDataKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form AdminDataObat
     */
    public DokterDataKaryawan() {
        initComponents();
    }

    public void setKaryawan(DefaultTableModel t) {
        datakaryawan.setModel(t);
    }

    public String getCari() {
        return cariTeks.getText();
    }

    public void setCari(String a) {
        cariTeks.setText(a);
    }

    public void cari(ActionListener a) {
        cariButton.addActionListener(a);
    }

    public void tambah(ActionListener a) {
        tambah.addActionListener(a);
    }

    public void ubahkaryawan(ActionListener t) {
        ubah.addActionListener(t);
    }
    
    public void hapus(ActionListener a){
        ubah1.addActionListener(a);
    }

    public void setUser(String a) {
        username.setText(a);
    }

    public JTable getTabel() {
        return datakaryawan;
    }

    public void tableListener(MouseListener m) {
        datakaryawan.addMouseListener(m);
    }

    public JButton ubahB() {
        return ubah;
    }
    
    public JButton hapusB() {
        return ubah1;
    }

    public void berandaListener(ActionListener a) {
        beranda.addActionListener(a);
    }

    public void pasienListener(ActionListener a) {
        pasien.addActionListener(a);
    }

    public JButton karyawanB() {
        return karyawan;
    }

    public JButton refreshO() {
        return refresh;
    }

    public void obatListener(ActionListener a) {
        obat.addActionListener(a);
    }

    public void refreshtabel(ActionListener a) {
        refresh.addActionListener(a);
    }

    public void karyawanListener(ActionListener a) {
        karyawan.addActionListener(a);
    }

    public void out(ActionListener a) {
        keluar.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        datakaryawan = new javax.swing.JTable();
        cariTeks = new javax.swing.JTextField();
        refresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cariButton = new javax.swing.JButton();
        ubah1 = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        beranda = new javax.swing.JButton();
        karyawan = new javax.swing.JButton();
        obat = new javax.swing.JButton();
        pasien = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datakaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(datakaryawan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 520, 290));

        cariTeks.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(cariTeks, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 210, 30));

        refresh.setBackground(new java.awt.Color(255, 255, 204));
        refresh.setFont(new java.awt.Font("Humnst777 BT", 1, 11)); // NOI18N
        refresh.setForeground(new java.awt.Color(89, 133, 39));
        refresh.setText("Refresh Tabel");
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 120, 30));

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel1.setText("Cari Karyawan:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 30));

        cariButton.setBackground(new java.awt.Color(255, 255, 204));
        cariButton.setFont(new java.awt.Font("Humnst777 BT", 1, 11)); // NOI18N
        cariButton.setForeground(new java.awt.Color(89, 133, 39));
        cariButton.setText("Cari");
        getContentPane().add(cariButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 70, 30));

        ubah1.setBackground(new java.awt.Color(102, 204, 0));
        ubah1.setFont(new java.awt.Font("Humnst777 BT", 1, 12)); // NOI18N
        ubah1.setForeground(new java.awt.Color(255, 255, 153));
        ubah1.setText("Hapus Karyawan");
        ubah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah1ActionPerformed(evt);
            }
        });
        getContentPane().add(ubah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 150, 40));

        ubah.setBackground(new java.awt.Color(102, 204, 0));
        ubah.setFont(new java.awt.Font("Humnst777 BT", 1, 12)); // NOI18N
        ubah.setForeground(new java.awt.Color(255, 255, 153));
        ubah.setText("Ubah Data");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 150, 40));

        username.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        username.setText("tes");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 70, 20));

        keluar.setBorder(null);
        keluar.setBorderPainted(false);
        keluar.setContentAreaFilled(false);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 50, 40));

        tambah.setBackground(new java.awt.Color(102, 204, 0));
        tambah.setFont(new java.awt.Font("Humnst777 BT", 1, 12)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 255, 153));
        tambah.setText("Tambah Karyawan");
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 150, 40));

        beranda.setBackground(new java.awt.Color(89, 133, 39));
        beranda.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 204));
        beranda.setText("Beranda");
        getContentPane().add(beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 40));

        karyawan.setBackground(new java.awt.Color(89, 133, 39));
        karyawan.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        karyawan.setForeground(new java.awt.Color(255, 255, 204));
        karyawan.setText("Data Karyawan");
        getContentPane().add(karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 150, 40));

        obat.setBackground(new java.awt.Color(89, 133, 39));
        obat.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        obat.setForeground(new java.awt.Color(255, 255, 204));
        obat.setText("Data Obat");
        getContentPane().add(obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 140, 40));

        pasien.setBackground(new java.awt.Color(89, 133, 39));
        pasien.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        pasien.setForeground(new java.awt.Color(255, 255, 204));
        pasien.setText("Data Pasien");
        getContentPane().add(pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/admin.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void ubah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubah1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DokterDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DokterDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DokterDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DokterDataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DokterDataKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beranda;
    private javax.swing.JButton cariButton;
    private javax.swing.JTextField cariTeks;
    private javax.swing.JTable datakaryawan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton karyawan;
    private javax.swing.JButton keluar;
    private javax.swing.JButton obat;
    private javax.swing.JButton pasien;
    private javax.swing.JButton refresh;
    private javax.swing.JButton tambah;
    private javax.swing.JButton ubah;
    private javax.swing.JButton ubah1;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
