/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dheta
 */
public class DokterLihatRMD extends javax.swing.JFrame {

    /**
     * Creates new form AdminLihatRMD
     */
    public DokterLihatRMD() {
        initComponents();
    }

    public void setNama(String a) {
        namaAdmin.setText(a);
    }

    public void setNamaPasien(String b) {
        nama.setText(b);
    }

    public void setTglLahir(String c) {
        tglLahir.setText(c);
    }

    public void setUsia(String a) {
        usia.setText(a);
    }
    
    public void setPekerjaan(String a){
        pekerjaan.setText(a);
    }
    
    public void setTelpon(String a){
        telpon.setText(a);
    }

    public void setAlamat(String d) {
        alamat.setText(d);
    }

    public void setJenisKelamin(String e) {
        jenisKelamin.setText(e);
    }

    public void setIDPasien(String a) {
        idPasien.setText(a);
    }

    public void setTabelRMD(DefaultTableModel t) {
        tabelRMD.setModel(t);
    }

    public void karyawanListener(ActionListener a) {
        karyawan.addActionListener(a);
    }

    public void berandaListener(ActionListener a) {
        beranda.addActionListener(a);
    }

    public void pasienListener(ActionListener a) {
        pasien.addActionListener(a);
    }
    
    public String getNama(){
        return nama.getText();
    }

    public JButton pasienB() {
        return pasien;
    }

    public JButton obatB() {
        return obat;
    }


    public JPanel tag() {
        return warna;
    }

    public void obatListener(ActionListener a) {
        obat.addActionListener(a);
    }

    public void kembaliListener(ActionListener a) {
        kembali.addActionListener(a);
    }

    public void ubahListener(ActionListener a) {
        ubah.addActionListener(a);
    }
    
    public void tambahListener(ActionListener a){
        tambahPeriksa.addActionListener(a);
    }
    
    public void keluaroi(ActionListener a){
        keluar.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        telpon = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelRMD = new javax.swing.JTable();
        ubah = new javax.swing.JButton();
        tambahPeriksa = new javax.swing.JButton();
        alamat = new javax.swing.JLabel();
        tglLahir = new javax.swing.JLabel();
        jenisKelamin = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usia = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        namaAdmin = new javax.swing.JLabel();
        beranda = new javax.swing.JButton();
        obat = new javax.swing.JButton();
        karyawan = new javax.swing.JButton();
        pasien = new javax.swing.JButton();
        pekerjaan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        warna = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        idPasien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel1.setText("Nama:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 30));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel2.setText("Tanggal Lahir:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 30));

        telpon.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(telpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 160, 30));

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel8.setText("Telepon  :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, 30));

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel3.setText("Jenis Kelamin:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, 30));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel4.setText("Alamat          :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, 30));

        tabelRMD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelRMD);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 750, 220));

        ubah.setBackground(new java.awt.Color(255, 255, 204));
        ubah.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        ubah.setForeground(new java.awt.Color(89, 133, 39));
        ubah.setText("Ubah Data Pasien");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, 30));

        tambahPeriksa.setBackground(new java.awt.Color(255, 255, 204));
        tambahPeriksa.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        tambahPeriksa.setForeground(new java.awt.Color(89, 133, 39));
        tambahPeriksa.setText("Tambah Data Periksa");
        tambahPeriksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPeriksaActionPerformed(evt);
            }
        });
        getContentPane().add(tambahPeriksa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, 30));

        alamat.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 280, 30));

        tglLahir.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(tglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 180, 30));

        jenisKelamin.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(jenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 130, 30));

        nama.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 190, 30));

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel5.setText("Usia saat ini  :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, 30));

        usia.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(usia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 100, 30));

        keluar.setBorder(null);
        keluar.setBorderPainted(false);
        keluar.setContentAreaFilled(false);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 50, 40));

        namaAdmin.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        namaAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        namaAdmin.setText("tes");
        getContentPane().add(namaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 240, 20));

        beranda.setBackground(new java.awt.Color(89, 133, 39));
        beranda.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 204));
        beranda.setText("Beranda");
        getContentPane().add(beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 40));

        obat.setBackground(new java.awt.Color(89, 133, 39));
        obat.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        obat.setForeground(new java.awt.Color(255, 255, 204));
        obat.setText("Data Obat");
        getContentPane().add(obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 140, 40));

        karyawan.setBackground(new java.awt.Color(89, 133, 39));
        karyawan.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        karyawan.setForeground(new java.awt.Color(255, 255, 204));
        karyawan.setText("Data Karyawan");
        getContentPane().add(karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 150, 40));

        pasien.setBackground(new java.awt.Color(89, 133, 39));
        pasien.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        pasien.setForeground(new java.awt.Color(255, 255, 204));
        pasien.setText("Data Pasien");
        getContentPane().add(pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 40));

        pekerjaan.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(pekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 280, 30));

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel7.setText("Pekerjaan      :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, 30));

        kembali.setBackground(new java.awt.Color(153, 255, 204));
        kembali.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        kembali.setForeground(new java.awt.Color(89, 133, 39));
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 30));

        warna.setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().add(warna, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 40, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/admin.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));
        getContentPane().add(idPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 60, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahPeriksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPeriksaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahPeriksaActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DokterLihatRMD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DokterLihatRMD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DokterLihatRMD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DokterLihatRMD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DokterLihatRMD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JButton beranda;
    private javax.swing.JLabel idPasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jenisKelamin;
    private javax.swing.JButton karyawan;
    private javax.swing.JButton keluar;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel namaAdmin;
    private javax.swing.JButton obat;
    private javax.swing.JButton pasien;
    private javax.swing.JLabel pekerjaan;
    private javax.swing.JTable tabelRMD;
    private javax.swing.JButton tambahPeriksa;
    private javax.swing.JLabel telpon;
    private javax.swing.JLabel tglLahir;
    private javax.swing.JButton ubah;
    private javax.swing.JLabel usia;
    private javax.swing.JPanel warna;
    // End of variables declaration//GEN-END:variables
}
