/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Dheta Delv-Indra
 */
public class DokterDaftarPeriksa extends javax.swing.JFrame {

    /**
     * Creates new form DokterDaftarPeriksa
     */
    public DokterDaftarPeriksa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sortMonth = new javax.swing.JButton();
        sortDate = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        range = new javax.swing.JButton();
        calender2 = new org.jdesktop.swingx.JXDatePicker();
        calender1 = new org.jdesktop.swingx.JXDatePicker();
        calender = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftarAntrian = new javax.swing.JTable();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        sortMonth.setBackground(new java.awt.Color(27, 179, 133));
        sortMonth.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        sortMonth.setForeground(new java.awt.Color(255, 255, 255));
        sortMonth.setText("bulan");
        sortMonth.setBorder(null);
        getContentPane().add(sortMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 80, 30));

        sortDate.setBackground(new java.awt.Color(27, 179, 133));
        sortDate.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        sortDate.setForeground(new java.awt.Color(255, 255, 255));
        sortDate.setText("tanggal");
        sortDate.setBorder(null);
        getContentPane().add(sortDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 90, 30));

        reset.setBackground(new java.awt.Color(27, 179, 133));
        reset.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("reset tabel");
        reset.setBorder(null);
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 110, 30));

        range.setBackground(new java.awt.Color(27, 179, 133));
        range.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        range.setForeground(new java.awt.Color(255, 255, 255));
        range.setText("rentang waktu");
        range.setBorder(null);
        getContentPane().add(range, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 130, 30));

        calender2.setBackground(new java.awt.Color(153, 153, 153));
        calender2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calender2ActionPerformed(evt);
            }
        });
        getContentPane().add(calender2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 150, -1));

        calender1.setBackground(new java.awt.Color(153, 153, 153));
        calender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calender1ActionPerformed(evt);
            }
        });
        getContentPane().add(calender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 150, -1));

        calender.setBackground(new java.awt.Color(255, 75, 109));
        calender.setForeground(new java.awt.Color(255, 255, 255));
        calender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calenderActionPerformed(evt);
            }
        });
        getContentPane().add(calender, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 150, -1));

        jLabel2.setText("akhir:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 70, -1));

        jLabel3.setText("awal:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, -1));

        daftarAntrian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(daftarAntrian);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 400, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calender2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calender2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calender2ActionPerformed

    private void calender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calender1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calender1ActionPerformed

    private void calenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DokterDaftarPeriksa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DokterDaftarPeriksa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DokterDaftarPeriksa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DokterDaftarPeriksa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DokterDaftarPeriksa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker calender;
    private org.jdesktop.swingx.JXDatePicker calender1;
    private org.jdesktop.swingx.JXDatePicker calender2;
    private javax.swing.JTable daftarAntrian;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton range;
    private javax.swing.JButton reset;
    private javax.swing.JButton sortDate;
    private javax.swing.JButton sortMonth;
    // End of variables declaration//GEN-END:variables
}
