/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dheta Delv-Indra
 */
public class DokterHome extends javax.swing.JFrame {

    /**
     * Creates new form DokterHome
     */
    public DokterHome() {
        initComponents();
    }

    public void setNama(String nama) {
        namaDokter.setText(nama);
    }

    public void setAntrian(DefaultTableModel t) {
        daftarAntrian.setModel(t);
    }

    public JButton berandaB() {
        return beranda;
    }

    public void tableListener(MouseListener m) {
        daftarAntrian.addMouseListener(m);
    }

    public void setTanggal(String tanggal) {
        Date y = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        today.setText(sdf.format(y));
    }

    public void setJumlah(String a) {
        jumlah.setText(a);
    }

    public void dataPasien(ActionListener a) {
        datapasien.addActionListener(a);
    }

    public void dataObat(ActionListener a) {
        dataobat.addActionListener(a);
    }

    public void refreshtabel(ActionListener a) {
        refresh.addActionListener(a);
    }

    public void dataKaryawan(ActionListener a) {
        karyawan.addActionListener(a);
    }

    public void periksaPasien(ActionListener a) {
        periksaPasien.addActionListener(a);
    }

    public void tambahantriListener(ActionListener a) {
        tambah.addActionListener(a);
    }

    public void logout(ActionListener a) {
        keluar.addActionListener(a);
    }

    public JButton periksa() {
        return periksaPasien;
    }

    public JButton karyawanB() {
        return karyawan;
    }

    public JButton refreshtab() {
        return refresh;
    }

    public JTable antrian() {
        return daftarAntrian;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        periksaPasien = new javax.swing.JButton();
        today = new javax.swing.JLabel();
        karyawan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        namaDokter = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        daftarAntrian = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        jumlah = new javax.swing.JLabel();
        datapasien = new javax.swing.JButton();
        dataobat = new javax.swing.JButton();
        beranda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        periksaPasien.setBackground(new java.awt.Color(255, 255, 204));
        periksaPasien.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        periksaPasien.setForeground(new java.awt.Color(89, 133, 39));
        periksaPasien.setText("Periksa Pasien");
        getContentPane().add(periksaPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 130, 40));

        today.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        today.setText("Daftar Antrian Hari ini,");
        getContentPane().add(today, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        karyawan.setBackground(new java.awt.Color(89, 133, 39));
        karyawan.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        karyawan.setForeground(new java.awt.Color(255, 255, 204));
        karyawan.setText("Data Karyawan");
        getContentPane().add(karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, 40));

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel3.setText("Jumlah Pasien Hari ini :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 30));

        namaDokter.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        namaDokter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        namaDokter.setText("tes");
        getContentPane().add(namaDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 210, 20));

        daftarAntrian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(daftarAntrian);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 620, 280));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel2.setText("Daftar Antrian Hari ini,");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        refresh.setBackground(new java.awt.Color(255, 255, 204));
        refresh.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        refresh.setForeground(new java.awt.Color(89, 133, 39));
        refresh.setText("Refresh Tabel");
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 130, 40));

        keluar.setBorder(null);
        keluar.setBorderPainted(false);
        keluar.setContentAreaFilled(false);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 50, 40));

        tambah.setBackground(new java.awt.Color(255, 255, 204));
        tambah.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        tambah.setForeground(new java.awt.Color(89, 133, 39));
        tambah.setText("Tambah Antrian");
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, 30));

        jumlah.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jumlah.setText("jLabel1");
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 60, 30));

        datapasien.setBackground(new java.awt.Color(89, 133, 39));
        datapasien.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        datapasien.setForeground(new java.awt.Color(255, 255, 204));
        datapasien.setText("Data Pasien");
        getContentPane().add(datapasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 40));

        dataobat.setBackground(new java.awt.Color(89, 133, 39));
        dataobat.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        dataobat.setForeground(new java.awt.Color(255, 255, 204));
        dataobat.setText("Data Obat");
        dataobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataobatActionPerformed(evt);
            }
        });
        getContentPane().add(dataobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 140, 40));

        beranda.setBackground(new java.awt.Color(89, 133, 39));
        beranda.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 204));
        beranda.setText("Beranda");
        getContentPane().add(beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/admin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataobatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataobatActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DokterHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DokterHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DokterHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DokterHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DokterHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beranda;
    private javax.swing.JTable daftarAntrian;
    private javax.swing.JButton dataobat;
    private javax.swing.JButton datapasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jumlah;
    private javax.swing.JButton karyawan;
    private javax.swing.JButton keluar;
    private javax.swing.JLabel namaDokter;
    private javax.swing.JButton periksaPasien;
    private javax.swing.JButton refresh;
    private javax.swing.JButton tambah;
    private javax.swing.JLabel today;
    // End of variables declaration//GEN-END:variables
}
