/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import model.obat;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Dheta Delv-Indra
 */
public class DokterPeriksaFinal extends javax.swing.JFrame {

    Connection konek;
    obat modelObat;
    int a = 0;
    int b = 0;
    int c = 0;
    int d = 0;

    /**
     * Creates new form DokterPeriksaFinal
     */
    public DokterPeriksaFinal() {
        initComponents();
    }

    public void setTanggal(String tgl) {
        tanggal.setText(tgl);
    }

    public void setIDRMD(String id) {
        idRMD.setText(id);
    }
    
    public void setUsername(String user){
        username.setText(user);
    }

    public void setNama(String nama) {
        namapasien.setText(nama);
    }

    public void setUmur(String nama) {
        umur.setText(nama);
    }

    public void setAlamat(String al) {
        alamat.setText(al);
    }

    public void setAnamnesa(String anam) {
        anamnesa.setText(anam);
    }

    public void setTensi(String tens) {
        tensi.setText(tens);
    }

    public void setNadi(String nad) {
        nadi.setText(nad);
    }

    public void setRR(String r) {
        rr.setText(r);
    }

    public void setSuhu(String su) {
        suhu.setText(su);
    }

    public void setDiagnosa(String d) {
        diagnosa.setText(d);
    }

    public void setKhusus(String kh) {
        khusus.setText(kh);
    }

    public void setTambahan(String t) {
        tambahan.setText(t);
    }
    
    public String getTarif(){
        return tarif.getText();
    }

    public void setTabelResep(DefaultTableModel t) {
        tabelResep.setModel(t);
    }
    
    public void selesaiperiksa(ActionListener a){
        done.addActionListener(a);
    }
    
    public void keluarok(ActionListener a){
        keluar.addActionListener(a);
    }
    
    
    public void berandaListener(ActionListener a){
        beranda.addActionListener(a);
    }
    
    public void obatListener(ActionListener a){
        dataobat.addActionListener(a);
    }
    
    public void karyawanListener(ActionListener a){
        karyawan.addActionListener(a);
    }

    public JButton karyawanB(){
    	return karyawan;
    }
    
    public JButton pasienB(){
    	return datapasien;
    }
    
    public JButton obatB(){
    	return dataobat;
    }
    
    public JButton berandaB(){
    	return beranda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelResep = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        cetakResep = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        namapasien = new javax.swing.JLabel();
        umur = new javax.swing.JLabel();
        tambahan = new javax.swing.JLabel();
        anamnesa = new javax.swing.JLabel();
        tensi = new javax.swing.JLabel();
        rr = new javax.swing.JLabel();
        suhu = new javax.swing.JLabel();
        nadi = new javax.swing.JLabel();
        diagnosa = new javax.swing.JLabel();
        khusus = new javax.swing.JLabel();
        done = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tarif = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        beranda = new javax.swing.JButton();
        datapasien = new javax.swing.JButton();
        dataobat = new javax.swing.JButton();
        karyawan = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        idRMD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel1.setText("Tanggal        :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 30));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel2.setText("Nama Pasien :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 30));

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel3.setText("Rp");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, 30));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel4.setText("Alamat          :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 30));

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel5.setText("Anamnesa     :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, 30));

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel6.setText("Diagnosa     :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, 30));

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel7.setText("Pemeriksaan Khusus     :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, 30));

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel8.setText("Suhu:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, 30));

        jLabel9.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel9.setText("Tensi:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, 30));

        jLabel10.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel10.setText("RR:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, 30));

        jLabel11.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel11.setText("Resep Obat");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        tabelResep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Obat", "Jumlah Obat", "Signa", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(tabelResep);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, 180));

        jLabel12.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel12.setText("Nadi:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, 30));

        cetakResep.setBackground(new java.awt.Color(255, 255, 204));
        cetakResep.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        cetakResep.setForeground(new java.awt.Color(89, 133, 39));
        cetakResep.setText("Cetak Resep");
        cetakResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakResepActionPerformed(evt);
            }
        });
        getContentPane().add(cetakResep, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, -1, 30));

        jLabel13.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel13.setText("Umur            :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 30));

        alamat.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 220, 30));

        tanggal.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 180, 30));

        namapasien.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(namapasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 190, 30));

        umur.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(umur, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 90, 30));

        tambahan.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        tambahan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tambahan.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(tambahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 290, 30));

        anamnesa.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        anamnesa.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(anamnesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 220, 30));

        tensi.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(tensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 50, 30));

        rr.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(rr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 80, 30));

        suhu.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(suhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 80, 30));

        nadi.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        getContentPane().add(nadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 50, 30));

        diagnosa.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        diagnosa.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(diagnosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 250, 30));

        khusus.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        khusus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        khusus.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(khusus, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 290, 30));

        done.setBackground(new java.awt.Color(255, 255, 204));
        done.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        done.setForeground(new java.awt.Color(89, 133, 39));
        done.setText("Selesai Periksa");
        getContentPane().add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, -1, 30));

        jLabel14.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel14.setText("Pemeriksaan Tambahan :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, 30));

        tarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifActionPerformed(evt);
            }
        });
        getContentPane().add(tarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 130, 30));

        jLabel15.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel15.setText("Tarif  :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, 30));

        beranda.setBackground(new java.awt.Color(89, 133, 39));
        beranda.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 204));
        beranda.setText("Beranda");
        getContentPane().add(beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 40));

        datapasien.setBackground(new java.awt.Color(89, 133, 39));
        datapasien.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        datapasien.setForeground(new java.awt.Color(255, 255, 204));
        datapasien.setText("Data Pasien");
        getContentPane().add(datapasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 40));

        dataobat.setBackground(new java.awt.Color(89, 133, 39));
        dataobat.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        dataobat.setForeground(new java.awt.Color(255, 255, 204));
        dataobat.setText("Data Obat");
        dataobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataobatActionPerformed(evt);
            }
        });
        getContentPane().add(dataobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 140, 40));

        karyawan.setBackground(new java.awt.Color(89, 133, 39));
        karyawan.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        karyawan.setForeground(new java.awt.Color(255, 255, 204));
        karyawan.setText("Data Karyawan");
        getContentPane().add(karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, 40));

        username.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        username.setText("tes");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 220, 20));

        keluar.setBorder(null);
        keluar.setBorderPainted(false);
        keluar.setContentAreaFilled(false);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 50, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/admin.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        idRMD.setText("jLabel14");
        getContentPane().add(idRMD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cetakResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakResepActionPerformed
        // TODO add your handling code here:
        JasperReport jasperReport;
        JasperPrint jasperPrint = null;
        try {
            JasperDesign jd2 = JRXmlLoader.load("report/resep.jrxml");
            DateFormat formatt = new SimpleDateFormat("yyyy-MM-dd");

            String query = "SELECT\n"
                    + "     obat.`namaObat`,\n"
                    + "     detailresep.`jumlah`,\n"
                    + "     detailresep.`signa`,\n"
                    + "     detailresep.`keterangan`,\n"
                    + "     pasien.`nama`,\n"
                    + "     pasien.`alamat`,\n"
                    + "     pasien.`pekerjaan`,\n"
                    + "     year(curdate())-year(pasien.`tanggalLahir`) as usia,\n"
                    + "     rekammedik.`tanggalPeriksa`\n"
                    + "     \n"
                    + "FROM  `detailresep` detailresep join `resepobat` resepobat \n"
                    + "on detailresep.`idResep`= resepobat.`idResep`  join \n"
                    + "`obat` obat on obat.`idObat`= detailresep.`idObat`  join \n"
                    + "`rekammedik` rekammedik on rekammedik.`idRM`=resepobat.`idRMD` join \n"
                    + "`pasien` pasien on pasien.`idPasien`= rekammedik.`idPasien` where `idRM`='" + idRMD.getText() + "'";

            System.out.println("cobababa");
            System.out.println(idRMD.getText());

            JRDesignQuery runquery2 = new JRDesignQuery();
            runquery2.setText(query);
            System.out.println("m" + b);
            jd2.setQuery(runquery2);
            jasperReport = JasperCompileManager.compileReport(jd2);
            try {
                jasperPrint = JasperFillManager.fillReport(
                        jasperReport, new HashMap(), DriverManager.getConnection("jdbc:mysql://localhost:3306/dokter", "root", ""));
            } catch (SQLException ex) {
                Logger.getLogger(DokterPeriksaFinal.class.getName()).log(Level.SEVERE, null, ex);
            }
            JasperViewer.viewReport(jasperPrint, false);
//            JasperExportManager.exportReportToPdfFile(jasperPrint, "src/main/java/com/blegoh/kasir/views/laporan/simple_report.pdf");
            System.out.println("lalalala2222");
        } catch (JRException ex) {
            Logger.getLogger(DokterPeriksaFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cetakResepActionPerformed

    private void dataobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataobatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataobatActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void tarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DokterPeriksaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DokterPeriksaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DokterPeriksaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DokterPeriksaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DokterPeriksaFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel anamnesa;
    private javax.swing.JButton beranda;
    private javax.swing.JButton cetakResep;
    private javax.swing.JButton dataobat;
    private javax.swing.JButton datapasien;
    private javax.swing.JLabel diagnosa;
    private javax.swing.JButton done;
    private javax.swing.JLabel idRMD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton karyawan;
    private javax.swing.JButton keluar;
    private javax.swing.JLabel khusus;
    private javax.swing.JLabel nadi;
    private javax.swing.JLabel namapasien;
    private javax.swing.JLabel rr;
    private javax.swing.JLabel suhu;
    private javax.swing.JTable tabelResep;
    private javax.swing.JLabel tambahan;
    private javax.swing.JLabel tanggal;
    private javax.swing.JTextField tarif;
    private javax.swing.JLabel tensi;
    private javax.swing.JLabel umur;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
