/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dheta Delv-Indra
 */
public class DokterDaftarPasien extends javax.swing.JFrame {

    /**
     * Creates new form DokterDaftarPasien
     */
    public DokterDaftarPasien() {
        initComponents();
    }
    
    public void setNama(String nama) {
        namaDokter.setText(nama);
    }
    
    public void setCari(String a) {
        cariTeks.setText(a);
    }
    
    public JButton detail() {
        return detailRMD;
    }

    public JTable getTabel() {
        return listPasien;
    }
    
    public void setTabelPasien(DefaultTableModel t) {
        listPasien.setModel(t);
    }

    public void tableListener(MouseListener m) {
        listPasien.addMouseListener(m);
    }
    
    public void cariButtonListener(ActionListener a) {
        cariButon.addActionListener(a);
    }
    
    public void detailListener(ActionListener b) {
        detailRMD.addActionListener(b);
    }
    
    public void karyawanListener(ActionListener a){
        karyawan.addActionListener(a);
    }
    
    public void berandaListener(ActionListener a){
        beranda.addActionListener(a);
    }
    
    public void obatListener(ActionListener a){
        obat.addActionListener(a);
    }
    
    public void tambahListener(ActionListener c) {
        tambah.addActionListener(c);
    }
    
    public void refreshtabel(ActionListener a){
        refresh.addActionListener(a);
    }
    
    public void keluardok(ActionListener a){
        keluar.addActionListener(a);
    }
    
    public String getCariPasien() {
        return cariTeks.getText();
    }
    
    public JButton pasien() {
        return datapasien;
    }
    
    public JButton refreshB(){
        return refresh;
    }
    
    public JButton cariB() {
        return cariButon;
    }

    public JButton karyawanB(){
    	return karyawan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listPasien = new javax.swing.JTable();
        cariTeks = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cariButon = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        detailRMD = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        beranda = new javax.swing.JButton();
        datapasien = new javax.swing.JButton();
        obat = new javax.swing.JButton();
        karyawan = new javax.swing.JButton();
        namaDokter = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(listPasien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 570, 320));

        cariTeks.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        cariTeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTeksActionPerformed(evt);
            }
        });
        getContentPane().add(cariTeks, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 240, 30));

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 0, 14)); // NOI18N
        jLabel1.setText("Cari Nama Pasien :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 30));

        cariButon.setBackground(new java.awt.Color(255, 255, 204));
        cariButon.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        cariButon.setForeground(new java.awt.Color(89, 133, 39));
        cariButon.setText("Cari");
        getContentPane().add(cariButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 70, 30));

        tambah.setBackground(new java.awt.Color(255, 255, 204));
        tambah.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        tambah.setForeground(new java.awt.Color(89, 133, 39));
        tambah.setText("Tambah Pasien");
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 120, 30));

        detailRMD.setBackground(new java.awt.Color(255, 255, 204));
        detailRMD.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        detailRMD.setForeground(new java.awt.Color(89, 133, 39));
        detailRMD.setText("Lihat Rekamedis Pasien");
        detailRMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailRMDActionPerformed(evt);
            }
        });
        getContentPane().add(detailRMD, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 170, 40));

        refresh.setBackground(new java.awt.Color(255, 255, 204));
        refresh.setFont(new java.awt.Font("Gisha", 1, 12)); // NOI18N
        refresh.setForeground(new java.awt.Color(89, 133, 39));
        refresh.setText("Refresh Tabel");
        getContentPane().add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 170, 40));

        beranda.setBackground(new java.awt.Color(89, 133, 39));
        beranda.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 204));
        beranda.setText("Beranda");
        getContentPane().add(beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 130, 40));

        datapasien.setBackground(new java.awt.Color(89, 133, 39));
        datapasien.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        datapasien.setForeground(new java.awt.Color(255, 255, 204));
        datapasien.setText("Data Pasien");
        getContentPane().add(datapasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 40));

        obat.setBackground(new java.awt.Color(89, 133, 39));
        obat.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        obat.setForeground(new java.awt.Color(255, 255, 204));
        obat.setText("Data Obat");
        obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obatActionPerformed(evt);
            }
        });
        getContentPane().add(obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 140, 40));

        karyawan.setBackground(new java.awt.Color(89, 133, 39));
        karyawan.setFont(new java.awt.Font("Geometr415 Blk BT", 0, 14)); // NOI18N
        karyawan.setForeground(new java.awt.Color(255, 255, 204));
        karyawan.setText("Data Karyawan");
        getContentPane().add(karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, 40));

        namaDokter.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        namaDokter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        namaDokter.setText("tes");
        getContentPane().add(namaDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 180, 20));

        keluar.setBorder(null);
        keluar.setBorderPainted(false);
        keluar.setContentAreaFilled(false);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 50, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/admin.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detailRMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailRMDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailRMDActionPerformed

    private void obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obatActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void cariTeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTeksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariTeksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DokterDaftarPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DokterDaftarPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DokterDaftarPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DokterDaftarPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DokterDaftarPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beranda;
    private javax.swing.JButton cariButon;
    private javax.swing.JTextField cariTeks;
    private javax.swing.JButton datapasien;
    private javax.swing.JButton detailRMD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton karyawan;
    private javax.swing.JButton keluar;
    private javax.swing.JTable listPasien;
    private javax.swing.JLabel namaDokter;
    private javax.swing.JButton obat;
    private javax.swing.JButton refresh;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
